POST http://localhost:8080/auth?name=Mikl&sex=M
Content-Type: application/json

###
GET http://localhost:8080/init
Accept: application/json

###
GET http://localhost:8080/users
Accept: application/json

###
POST http://localhost:8080/messages
Content-Type: application/json

hello 3
###
GET http://localhost:8080/messages?offset=0&limit=50
Accept: application/json

###
GET http://localhost:8080/404
Accept: application/json

###