POST http://localhost:8080/auth?name=Mikl&sex=M
Content-Type: application/json

###
GET http://localhost:8080/init
Accept: application/json

###
GET http://localhost:8080/users
Accept: application/json

###
POST http://localhost:8080/messages
Content-Type: application/json

hello

###
GET http://localhost:8080/messages?offset=1&limit=1
Accept: application/json

###